GET http://localhost:4000/
###

GET http://localhost:4000/status
###

###
GET http://localhost:4000/blocks

###
GET http://localhost:4000/wallet
###

POST http://localhost:4000/blocks

###
POST http://localhost:4000/balance/522d428d05e5746edf1630e8140314712b00b5a7059bbc7afa51d3b8d32da1275a0796fa51612d20e15b49b646e99678fdf252038dd5f9c7e0f7b7e5f0b12594

{
    "message":"Mine me"
}
###
POST http://localhost:4000/transactions

{
    "to":"woo",
    "amount":5
}
###

http://localhost:4000/mempool

###
http://localhost:4000/balance/woo?total=true
###
http://localhost:4000/balance/woo
